# -*- coding: utf-8 -*-
"""Amazon_sales_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVs43xM1WP6pum_cYV8M_dogIdbHBMl5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("amazon_sales_data 2025.csv")
df_clean= df.copy()

df_clean.columns =(
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)

df_clean.columns

df.head()
df.tail()
df.info()
df.shape
df.describe()

cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include= ['int64']).columns.tolist()

print("Categorical columns:", cat_cols)
print("Numerical columns:", num_cols)

for col in cat_cols:
  print(f"\nValue counts for '{col}':")
  print(df[col].value_counts())

print(df.isnull().sum())

print(df.duplicated().sum())

df_clean.to_csv("Amazon_clean.csv", index=False)

